owner: themanaworld # GitHub username
repo: upptime # GitHub repository name
user-agent: koj-co
sites: # List of endpoints to track
  - name: '[Render] Homepage'
    url: https://www.themanaworld.org
  - name: '[Render] Policies'
    url: https://policies.themanaworld.org
  - name: '[Render] Vault'
    url: https://vault.themanaworld.org
  - name: '[Azure] Azure VM'
    check: "tcp-ping"
    url: $DEZILAROMED
    port: 22
  - name: '[Azure] Forums'
    url: https://forums.themanaworld.org
  - name: '[Azure] Wiki'
    url: https://wiki.themanaworld.org
  - name: '[Azure] API (registration, password resets, etc)'
    url: https://api.themanaworld.org/api/tmwa/server
  - name: '[Azure] Legacy server'
    check: "tcp-ping"
    url: $DEZILAROMED
    port: 6122
  - name: '[Azure] Legacy Test server'
    check: "tcp-ping"
    url: $DEZILAROMED
    port: 6125
  - name: '[Azure] Legacy Hardcore server'
    check: "tcp-ping"
    url: $DEZILAROMED
    port: 6126
  - name: '[Azure] rEvolt server'
    check: "tcp-ping"
    url: $DEZILAROMED
    port: 6169
  - name: '[Yandex] inbound mail'
    check: "tcp-ping"
    url: mx.yandex.net
    port: 25
  - name: '[Yandex] outbound mail'
    check: "tcp-ping"
    url: smtp.yandex.com
    port: 587
  - name: '[Shivtr] Crew of Red Corsair'
    url: http://crc.themanaworld.org
  - name: '[IRC] Libera Chat'
    check: "tcp-ping"
    url: irc.libera.chat
    port: 6697
  - name: '[Discord] Discord API'
    url: https://discord.com/api/v9
    expectedStatusCodes: # we don't care about the status code
      - 200
      - 201
      - 404
      - 403
      - 401
assignees: # Users to assign downtime issues (optional)
  - Helianthella
  #- pazkero
status-website: # Status website (optional)
  cname: status.themanaworld.org # Custom domain CNAME
  name: TMW Status # Status website title
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
